/** Read-only v6 material/role/port and negative-coordinate small-hole regression.
 * Derives expectations from declarations and topology, never from builder masks.
 * Does not claim that every artistic jaggy/double can be classified automatically.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {CANONICAL_MASKS,RAW_TO_CANONICAL,RAW_TO_INDEX,QUARTER_MODULE_KEYS,getQuadrants,occupancyFromRows,resolveCell,partitionOccupancy} from './terrain_topology.mjs';
import {resolveVariant} from './terrain_composition.mjs';
const require=createRequire(import.meta.url),sharp=require('sharp');
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),args=process.argv.slice(2);
const option=(n,f)=>args.includes(n)?args[args.indexOf(n)+1]:f;
const BASELINE=path.resolve(ROOT,option('--baseline-v5','../ANIMOL_FreeShape_Sprites_hole_finish_v5'));
const REPORT=path.resolve(ROOT,option('--report','Docs/theme_finish_validation.json'));
const errors=[],checks={},cache=new Map(),start=performance.now();let failureCount=0;
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function verify(ok,label,detail){if(ok)return;failureCount++;if(errors.length<100)errors.push({label,...(detail===undefined?{}:{detail})});}
const json=async(root,name)=>JSON.parse(await fs.readFile(path.join(root,name),'utf8'));
async function image(root,name){const file=path.resolve(root,name);if(!cache.has(file))cache.set(file,(async()=>{const bytes=await fs.readFile(file),{data,info}=await sharp(bytes).ensureAlpha().raw().toBuffer({resolveWithObject:true});return{bytes,data,width:info.width,height:info.height};})());return cache.get(file);}
const blank=(w,h)=>({width:w,height:h,data:Buffer.alloc(w*h*4)}),index=(im,x,y)=>(y*im.width+x)*4,mod=(a,b)=>(a%b+b)%b;
const colors=new Map();function color(c){if(!colors.has(c))colors.set(c,Buffer.from([...c.slice(1).match(/../gu).map(v=>parseInt(v,16)),255]));return colors.get(c);}
function put(im,x,y,c,toroidal=false){if(toroidal){x=mod(x,im.width);y=mod(y,im.height);}if(x>=0&&y>=0&&x<im.width&&y<im.height)color(c).copy(im.data,index(im,x,y));}
function compare(actual,expected,label){if(actual.width!==expected.width||actual.height!==expected.height){verify(false,label+' dimensions',{actual:[actual.width,actual.height],expected:[expected.width,expected.height]});return expected.width*expected.height;}let count=0,examples=[];for(let p=0;p<expected.data.length;p+=4)if(!actual.data.subarray(p,p+4).equals(expected.data.subarray(p,p+4))){count++;if(examples.length<4)examples.push({x:p/4%expected.width,y:Math.floor(p/4/expected.width),actual:actual.data.subarray(p,p+4).toString('hex'),expected:expected.data.subarray(p,p+4).toString('hex')});}verify(count===0,label+' exact RGBA',{mismatches:count,examples});return count;}
async function pngFiles(directory){const result=[];for(const e of await fs.readdir(directory,{withFileTypes:true})){const p=path.join(directory,e.name);if(e.isDirectory())result.push(...await pngFiles(p));else if(e.name.endsWith('.png'))result.push(p);}return result;}
async function styleFiles(root,id){return[...await pngFiles(path.join(root,'Art',id)),...await pngFiles(path.join(root,'Samples',id)),...(await fs.readdir(path.join(root,'Art/Atlases'))).filter(n=>n.startsWith(id+'_')&&n.endsWith('.png')).map(n=>path.join(root,'Art/Atlases',n))].map(n=>path.relative(root,n).split(path.sep).join('/')).sort();}
function normalized(p){const b=p.body??{},t=p.trim??{},e=p.edges??t.edges??{};return{...p,outline:p.outline??'#1a1c2c',body:{...b,base:b.base??b.baseColor??'#1a1c2c',ops:b.ops??[...(b.faces??[]).map(o=>({kind:'face',...o})),...(b.lines??[]).map(o=>({kind:'rect',...o})),...(b.polygons??[]).map(o=>({kind:'polygon',...o}))]},edges:{N:e.N??t.top,S:e.S??t.bottom,W:e.W??t.side,E:e.E??t.side}};}
function rectangle(im,r,c,toroidal=true){for(let y=r.y;y<r.y+r.h;y++)for(let x=r.x;x<r.x+r.w;x++)put(im,x,y,c,toroidal);}
function face(im,r,toroidal=true){const inset=r.highlightInset??r.highlightInsetPixels??2;for(let y=0;y<r.h;y++)for(let x=0;x<r.w;x++){if((r.radius??r.cornerRadiusPixels??0)===1&&(x===0||x===r.w-1)&&(y===0||y===r.h-1))continue;put(im,r.x+x,r.y+y,r.highlightColor&&y===0&&x>=inset&&x<r.w-inset?r.highlightColor:r.shadowColor&&y===r.h-1?r.shadowColor:r.color??r.c,toroidal);}}
// Winding number uses a different membership algorithm from the production
// builder's crossing toggle; centers are sampled only on the integer grid.
function polygon(im,r){const pts=r.points;const side=(a,b,x,y)=>(b[0]-a[0])*(y-a[1])-(x-a[0])*(b[1]-a[1]);function contains(x,y){let winding=0;for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length];if(a[1]<=y&&b[1]>y&&side(a,b,x,y)>0)winding++;else if(a[1]>y&&b[1]<=y&&side(a,b,x,y)<0)winding--;}return winding!==0;}const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),membership=new Uint8Array(4096);for(let y=Math.min(...ys);y<Math.max(...ys);y++)for(let x=Math.min(...xs);x<Math.max(...xs);x++)if(contains(x+.5,y+.5))membership[mod(y,64)*64+mod(x,64)]=1;for(let y=0;y<64;y++)for(let x=0;x<64;x++)if(membership[y*64+x]){const edge=r.outline&&[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>!membership[mod(y+dy,64)*64+mod(x+dx,64)]);put(im,x,y,edge?r.outline:r.color,true);}}
function material(p){const im=blank(64,64);rectangle(im,{x:0,y:0,w:64,h:64},p.body.base);for(const r of p.body.ops.filter(o=>o.kind==='face'))rectangle(im,{x:r.x-1,y:r.y-1,w:r.w+2,h:r.h+2},r.outline??p.outline);for(const r of p.body.ops){if(r.kind==='face')face(im,r);else if(r.kind==='rect'||r.kind==='line')rectangle(im,r,r.color??r.c);else if(r.kind==='polygon')polygon(im,r);else verify(false,'Unrecognized registered material operation',r);}return im;}
function role(p,corner,state){const im=blank(16,16),west=corner.endsWith('W'),north=corner.startsWith('N'),h=p.edges[north?'N':'S'],v=p.edges[west?'W':'E'];for(let y=0;y<16;y++)for(let x=0;x<16;x++){const dx=west?x:15-x,dy=north?y:15-y;let c;
  if(state==='TOP'||state==='BOTTOM'){if(dy<h.length)c=h[dy];}
  else if(state==='SIDE'){if(dx<v.length)c=v[dx];}
  else if(state==='OUTER'){if(dx<v.length)c=v[dx];if(dy<h.length)c=h[dy];if(dx===0||dy===0)c=p.outline;}
  else if(state==='INNER'&&dx<v.length&&dy<h.length){c=dx===0?h[dy]:dy===0?v[dx]:dx===v.length-1?v[dx]:h[dy];}
  if(c)put(im,x,y,c);
}const ornaments=(state==='OUTER'?p.outerCorner:state==='INNER'?p.innerCorner:null)?.ornamentFaces??[];for(const r of ornaments){verify(r.x>=1&&r.y>=1&&r.x+r.w<=14&&r.y+r.h<=14,'Ornament touches immutable attachment port',{styleId:p.styleId,state,r});if(state==='INNER')verify(r.x-1>=0&&r.y-1>=0&&r.x+r.w<v.length&&r.y+r.h<h.length,'Inner ornament/halo exceeds trim intersection and could create a fin',{styleId:p.styleId,corner,r,band:[v.length,h.length]});const tmp=blank(16,16);rectangle(tmp,{x:r.x-1,y:r.y-1,w:r.w+2,h:r.h+2},p.outline,false);face(tmp,r,false);for(let y=1;y<15;y++)for(let x=1;x<15;x++){const q=index(tmp,x,y);if(tmp.data[q+3])tmp.data.copy(im.data,index(im,west?x:15-x,north?y:15-y),q,q+4);}}return im;}
function compose(core,overlay,corner,variant){const im=blank(16,16),sx=(variant&1)*32+(corner.endsWith('W')?0:16),sy=(variant>>1)*32+(corner.startsWith('N')?0:16);im.owners=new Uint8Array(256);for(let y=0;y<16;y++)for(let x=0;x<16;x++){const a=index(overlay,x,y),b=index(core,sx+x,sy+y),owned=overlay.data[a+3]===255;const src=owned?overlay:core,q=owned?a:b;src.data.copy(im.data,index(im,x,y),q,q+4);im.owners[y*16+x]=Number(owned);}return im;}
function assemble(modules,quadrants){const im=blank(32,32);for(const q of quadrants)for(let y=0;y<16;y++)for(let x=0;x<16;x++){const p=index(modules[q.moduleKey],x,y);modules[q.moduleKey].data.copy(im.data,index(im,q.column*16+x,q.row*16+y),p,p+4);}return im;}
const offsets=[[0,1,1],[1,1,2],[1,0,4],[1,-1,8],[0,-1,16],[-1,-1,32],[-1,0,64],[-1,1,128]];
function topology(set,x,y){if(!set.has(`${x},${y}`))return null;let raw=0;for(const[dx,dy,bit]of offsets)if(set.has(`${x+dx},${y+dy}`))raw|=bit;let mask=raw;for(const[v,h,d]of[[1,64,128],[1,4,2],[16,64,32],[16,4,8]])if(!(raw&v)||!(raw&h))mask&=~d;return{raw,mask};}
function clusters(im){const visited=new Uint8Array(im.width*im.height),out={nonInkSmallClusters:0,isolatedNonInkPixels:0,examples:[]};for(let n=0;n<visited.length;n++){if(visited[n])continue;const p=n*4,c=im.data.subarray(p,p+4).toString('hex'),queue=[n];visited[n]=1;for(let k=0;k<queue.length;k++){const at=queue[k],x=at%im.width,y=Math.floor(at/im.width);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const next=mod(y+dy,im.height)*im.width+mod(x+dx,im.width);if(!visited[next]&&im.data.subarray(next*4,next*4+4).toString('hex')===c){visited[next]=1;queue.push(next);}}}if(c==='1a1c2cff'||c.endsWith('00')||queue.length>3)continue;out.nonInkSmallClusters++;if(queue.length===1)out.isolatedNonInkPixels++;if(out.examples.length<8)out.examples.push({color:'#'+c.slice(0,6),area:queue.length,pixels:queue.map(v=>[v%im.width,Math.floor(v/im.width)])});}return out;}

const lookup=await json(ROOT,'Data/sprite_lookup.json'),preservation=await json(ROOT,'Data/v5_preservation_manifest.json');
const hasBaseline=await fs.access(path.join(BASELINE,'Data/sprite_lookup.json')).then(()=>true,()=>false);
if(args.includes('--baseline-v5')&&!hasBaseline)throw Error('The explicitly requested --baseline-v5 package is missing: '+BASELINE);
const packagedBaseline=args.includes('--packaged-baseline')||!hasBaseline;
verify(preservation.schemaVersion===1&&preservation.provenance?.sourceArtVersion===5&&preservation.globalContracts?.artVersion===5,'Bundled preservation manifest is not an authoritative v5 capture');
verify(preservation.lockedT01APngs?.length===295&&preservation.motifPngs?.length===20&&preservation.bodyFields?.length===20&&preservation.unchangedDataFiles?.length===3&&preservation.lockedT01AStyle?.styleId==='T01_A','Bundled v5 preservation evidence is incomplete');
const oldLookup=packagedBaseline?{...preservation.globalContracts,styles:preservation.styles.map(s=>s.styleId==='T01_A'?preservation.lockedT01AStyle:s)}:await json(BASELINE,'Data/sprite_lookup.json');
if(!packagedBaseline)verify(hash(await fs.readFile(path.join(BASELINE,'Data/sprite_lookup.json')))===preservation.provenance.sourceLookupSha256,'Fresh v5 lookup differs from the captured preservation authority');
checks.preservationAuthority={mode:packagedBaseline?'bundled exact v5 PNG/RGBA SHA256 and complete T01_A metadata':'actual v5 package plus bundled exact SHA256 provenance',file:'Data/v5_preservation_manifest.json',fileSha256:hash(await fs.readFile(path.join(ROOT,'Data/v5_preservation_manifest.json'))),sourcePackage:preservation.provenance.sourcePackage,sourceLookupSha256:preservation.provenance.sourceLookupSha256,explicitPackagedBaseline:args.includes('--packaged-baseline'),baselineSiblingAvailable:hasBaseline};
verify(lookup.artVersion===6&&lookup.schemaVersion===1&&lookup.contractId==='ANIMOL_FREE_SHAPE_BLOB47_V1'&&lookup.cellPixels===32&&lookup.pixelsPerUnit===32,'Active v6 art/occupancy contract differs');
for(const k of['palette','transparentRGB','alphaValues','cellArtAlpha','phase','macroMotif'])verify(same(lookup[k],oldLookup[k]),'Stable lookup contract changed: '+k);
verify(same(lookup.canonicalMasks,CANONICAL_MASKS)&&same(lookup.rawToCanonical,RAW_TO_CANONICAL)&&same(lookup.rawToIndex,RAW_TO_INDEX),'47-mask canonical topology changed');
verify(lookup.styles.length===20&&same(lookup.styles.map(s=>s.styleId),oldLookup.styles.map(s=>s.styleId)),'20-style theme inventory changed');
for(const record of preservation.unchangedDataFiles){const current=await fs.readFile(path.join(ROOT,record.file));verify(current.length===record.bytes&&hash(current)===record.sha256,'Approved catalog/fixture/palette SHA changed: '+record.file);if(!packagedBaseline)verify(current.equals(await fs.readFile(path.join(BASELINE,record.file))),'Approved catalog/fixture/palette changed: '+record.file);}
checks.contract={artVersion:lookup.artVersion,contractId:lookup.contractId,schemaVersion:lookup.schemaVersion,cellPixels:lookup.cellPixels,pixelsPerUnit:lookup.pixelsPerUnit,styles:lookup.styles.length,canonicalMasks:lookup.canonicalMasks.length,occupancyContractUnchanged:true};
checks.lockedT01A={pngFiles:0,bytes:0,byteMismatches:0,metadataUnchanged:true};
verify(same(lookup.styles.find(s=>s.styleId==='T01_A'),oldLookup.styles.find(s=>s.styleId==='T01_A')),'T01_A v5 approved style metadata changed');
const lockedFiles=await styleFiles(ROOT,'T01_A'),lockedRecords=new Map(preservation.lockedT01APngs.map(r=>[r.file,r]));verify(same(lockedFiles,[...lockedRecords.keys()]),'T01_A v5 PNG inventory differs from captured authority');if(!packagedBaseline)verify(same(lockedFiles,await styleFiles(BASELINE,'T01_A')),'T01_A v5 PNG inventory changed');for(const file of lockedFiles){const a=await fs.readFile(path.join(ROOT,file)),r=lockedRecords.get(file);checks.lockedT01A.pngFiles++;checks.lockedT01A.bytes+=a.length;const matches=r&&a.length===r.bytes&&hash(a)===r.sha256;if(!matches)checks.lockedT01A.byteMismatches++;if(!packagedBaseline)verify(a.equals(await fs.readFile(path.join(BASELINE,file))),'T01_A PNG differs from actual v5 package: '+file);}verify(checks.lockedT01A.byteMismatches===0,'T01_A v5 approved PNG bytes changed',checks.lockedT01A);
checks.approvedSourceAndMotifs={sourcePngFiles:0,motifs:0,byteMismatches:0};
for(const r of preservation.originalSourceArtPngs){const a=await fs.readFile(path.join(ROOT,r.file));checks.approvedSourceAndMotifs.sourcePngFiles++;if(a.length!==r.bytes||hash(a)!==r.sha256)checks.approvedSourceAndMotifs.byteMismatches++;if(!packagedBaseline)verify(a.equals(await fs.readFile(path.join(BASELINE,r.file))),'Original source differs from actual v5 package: '+r.file);}
const motifRecords=new Map(preservation.motifPngs.map(r=>[r.styleId,r]));for(const s of lookup.styles){const previous=oldLookup.styles.find(p=>p.styleId===s.styleId),r=motifRecords.get(s.styleId),a=await fs.readFile(path.join(ROOT,s.panels.motif));verify(s.panels.motif===previous.panels.motif&&s.panels.motif===r?.file,'Approved motif registration changed: '+s.styleId);if(!r||a.length!==r.bytes||hash(a)!==r.sha256)checks.approvedSourceAndMotifs.byteMismatches++;if(!packagedBaseline)verify(a.equals(await fs.readFile(path.join(BASELINE,previous.panels.motif))),'Motif differs from actual v5 package: '+s.styleId);checks.approvedSourceAndMotifs.motifs++;}
verify(checks.approvedSourceAndMotifs.byteMismatches===0,'Approved source art or motif PNG changed',checks.approvedSourceAndMotifs);
const profiles=new Map();for(const name of(await fs.readdir(path.join(ROOT,'Data/native_v6'))).filter(n=>n.endsWith('.json')).sort()){const doc=await json(ROOT,'Data/native_v6/'+name);for(const raw of doc.styles??[doc]){const p=normalized(raw);verify(!profiles.has(p.styleId),'Duplicate native style profile: '+p.styleId);profiles.set(p.styleId,p);}}
verify(profiles.size===19&&!profiles.has('T01_A'),'Exactly 19 revised styles expected; T01_A must stay v5');
const exactPalette=new Set(lookup.palette.map(c=>c.slice(1)+'ff')),moduleSets=new Map(),cellSets=new Map();
checks.revisedStyles=[];checks.finalExports={styles:0,quarterModules:0,cells:0,quarterRgbaMismatches:0,cellRgbaMismatches:0,maskMismatches:0,bodyPixelsChecked:0,bodyPixelMismatches:0,paletteOrAlphaFailures:0,atlasPixelMismatches:0};
checks.ports={rolePixelsChecked:0,straightOuterAttachmentPixels:0,innerAttachmentPixels:0,innerOppositeTransparentPixels:0,unexpectedInnerFinPixels:0,rgbaMismatches:0};
for(const style of lookup.styles){const p=profiles.get(style.styleId),modulesByVariant=[],cellsByVariant=[];let core,roles;
  if(p){const registration=style.nativeSourceProfile;verify(style.decorativeSampling.junctionOverlayProfile==='native-quarter-roles-v6'&&registration?.quarterRoleSources,'Native semantic role metadata missing: '+style.styleId);for(const[direction,band]of Object.entries(p.edges))verify(Array.isArray(band)&&band.length>=2&&band.length<=8&&band[0]===p.outline&&band.at(-1)===p.outline&&band.every(c=>lookup.palette.includes(c)),'Invalid directional attachment profile',{styleId:style.styleId,direction,band});core=material(p);const actualCore=await image(ROOT,registration.materialRepeat64);compare(actualCore,core,style.styleId+' declared 64px body');const reference=await image(ROOT,registration.materialReference128),field=await image(ROOT,style.materialSampling.repeatedField);let repeatMismatches=0;for(const target of[reference,field]){verify(target.width===128&&target.height===128,'Native repeat field must be 128px: '+style.styleId);const offset=target===field?32:0;for(let y=0;y<128;y++)for(let x=0;x<128;x++){const cp=index(core,mod(x-offset,64),mod(y-offset,64));if(!target.data.subarray(index(target,x,y),index(target,x,y)+4).equals(core.data.subarray(cp,cp+4)))repeatMismatches++;}}const oldBodyRecord=preservation.bodyFields.find(s=>s.styleId===style.styleId);verify(oldBodyRecord&&hash(field.data)!==oldBodyRecord.rgbaSha256,'Revised body still equals old artwork: '+style.styleId);if(!packagedBaseline){const oldBody=await image(BASELINE,oldLookup.styles.find(s=>s.styleId===style.styleId).materialSampling.repeatedField);verify(hash(oldBody.data)===oldBodyRecord.rgbaSha256,'Actual v5 body differs from the captured RGBA authority: '+style.styleId);verify(!field.data.equals(oldBody.data),'Revised body still equals actual v5 artwork: '+style.styleId);}verify(repeatMismatches===0,'Material repeat field drifted from native 64px body',{styleId:style.styleId,repeatMismatches});
    roles={};for(const key of QUARTER_MODULE_KEYS){const[corner,state]=key.split('_');roles[key]=role(p,corner,state);const actual=await image(ROOT,registration.quarterRoleSources[key]);compare(actual,roles[key],style.styleId+' role/'+key);const west=corner.endsWith('W'),north=corner.startsWith('N'),h=p.edges[north?'N':'S'],v=p.edges[west?'W':'E'];for(let y=0;y<16;y++)for(let x=0;x<16;x++){const dx=west?x:15-x,dy=north?y:15-y,a=index(actual,x,y);checks.ports.rolePixelsChecked++;if(state==='INNER'&&actual.data[a+3]&&(dx>=v.length||dy>=h.length))checks.ports.unexpectedInnerFinPixels++;}
      for(let t=0;t<16;t++){const x=west?0:15,y=north?t:15-t,a=index(actual,x,y),xx=west?t:15-t,yy=north?0:15,b=index(actual,xx,yy);const hx=h[t]?color(h[t]):Buffer.alloc(4),vx=v[t]?color(v[t]):Buffer.alloc(4);if(state==='INNER'){if(!actual.data.subarray(a,a+4).equals(hx))checks.ports.rgbaMismatches++;if(!actual.data.subarray(b,b+4).equals(vx))checks.ports.rgbaMismatches++;checks.ports.innerAttachmentPixels+=2;const ox=west?15:0,oy=north?15:0;for(const q of[index(actual,ox,t),index(actual,t,oy)]){if(!actual.data.subarray(q,q+4).equals(Buffer.alloc(4)))checks.ports.rgbaMismatches++;checks.ports.innerOppositeTransparentPixels++;}}
        if(state==='OUTER'){const edgeX=west?15:0,edgeY=north?15:0;if(!actual.data.subarray(index(actual,edgeX,y),index(actual,edgeX,y)+4).equals(hx))checks.ports.rgbaMismatches++;if(!actual.data.subarray(index(actual,xx,edgeY),index(actual,xx,edgeY)+4).equals(vx))checks.ports.rgbaMismatches++;checks.ports.straightOuterAttachmentPixels+=2;}}
    }
    const bodyColors=[...new Set(Array.from({length:4096},(_,n)=>actualCore.data.subarray(n*4,n*4+3).toString('hex')))];verify(p.body.ops.length>=4&&bodyColors.length>=3,'Theme material lacks declared structural detail: '+style.styleId,{operations:p.body.ops.length,colors:bodyColors.length});
    const geometry={faces:0,roundedFaces:0,highlightFaces:0,shadowFaces:0,rectangles:0,polygons:0,onePixelNoiseDeclarations:0};for(const o of p.body.ops){if(o.kind==='face'){geometry.faces++;geometry.roundedFaces+=Number((o.radius??o.cornerRadiusPixels??0)===1);geometry.highlightFaces+=Number(Boolean(o.highlightColor));geometry.shadowFaces+=Number(Boolean(o.shadowColor));if(o.w<4||o.h<4)geometry.onePixelNoiseDeclarations++;}else if(o.kind==='polygon')geometry.polygons++;else{geometry.rectangles++;if(o.w*o.h<4)geometry.onePixelNoiseDeclarations++;}}verify(geometry.onePixelNoiseDeclarations===0,'Body declares isolated or too-small noise shapes: '+style.styleId,geometry);
    checks.revisedStyles.push({styleId:style.styleId,materialDescription:p.materialDescription??null,materialSha256:hash(actualCore.bytes),native64ComparedPixels:4096,repeatedFieldComparedPixels:32768,repeatMismatches,bodyColors:bodyColors.map(c=>'#'+c),geometry,toroidalColorClusterCandidates:clusters(actualCore),clusterCandidateMeaning:'Color components of 1..3 pixels are candidates for visual review. Registered face highlights/shadows and rounded cuts are assessed by declarations; no blanket all-jaggies-zero claim.'});
  }
  for(const variant of style.variants){const v=variant.phaseX+variant.phaseY*2,modules={},cells=new Map();verify(variant.id==='v'+v&&[0,1].includes(variant.phaseX)&&[0,1].includes(variant.phaseY),'Variant phase registration changed: '+style.styleId+'/'+variant.id);for(const key of QUARTER_MODULE_KEYS){const actual=await image(ROOT,variant.modules[key]),corner=key.split('_')[0],expected=p?compose(core,roles[key],corner,v):packagedBaseline?actual:await image(BASELINE,oldLookup.styles.find(s=>s.styleId===style.styleId).variants[v].modules[key]);modules[key]=expected;checks.finalExports.quarterRgbaMismatches+=compare(actual,expected,style.styleId+'/'+variant.id+'/'+key);const rows=variant.junctionOverlayMasks?.[key];verify(Array.isArray(rows)&&rows.length===16&&rows.every(r=>/^[01]{16}$/u.test(r)),'Invalid role ownership mask: '+style.styleId+'/'+variant.id+'/'+key);if(p)for(let y=0;y<16;y++)for(let x=0;x<16;x++)if(String(expected.owners[y*16+x])!==rows?.[y]?.[x])checks.finalExports.maskMismatches++;checks.finalExports.quarterModules++;}
    const atlas=await image(ROOT,variant.atlas);for(const record of variant.cells){const expected=assemble(modules,getQuadrants(record.mask)),actual=await image(ROOT,record.file);checks.finalExports.cellRgbaMismatches+=compare(actual,expected,style.styleId+'/'+variant.id+'/mask'+record.mask);cells.set(record.mask,actual);for(let y=0;y<32;y++)for(let x=0;x<32;x++){const a=index(actual,x,y),b=index(atlas,record.rect.x+x,record.rect.y+y),hex=actual.data.subarray(a,a+4).toString('hex');if(!exactPalette.has(hex)||actual.data[a+3]!==255)checks.finalExports.paletteOrAlphaFailures++;if(!actual.data.subarray(a,a+4).equals(atlas.data.subarray(b,b+4)))checks.finalExports.atlasPixelMismatches++;if(p){const q=getQuadrants(record.mask)[(y>=16?2:0)+(x>=16?1:0)],owned=modules[q.moduleKey].owners[(y%16)*16+x%16];if(!owned){const bp=index(core,variant.phaseX*32+x,variant.phaseY*32+y);checks.finalExports.bodyPixelsChecked++;if(!actual.data.subarray(a,a+4).equals(core.data.subarray(bp,bp+4)))checks.finalExports.bodyPixelMismatches++;}}}checks.finalExports.cells++;}
    modulesByVariant[v]=modules;cellsByVariant[v]=cells;
  }moduleSets.set(style.styleId,modulesByVariant);cellSets.set(style.styleId,cellsByVariant);checks.finalExports.styles++;
}
verify(checks.finalExports.quarterModules===1600&&checks.finalExports.cells===3760&&checks.finalExports.styles===20,'Final export inventory is incomplete',checks.finalExports);
for(const field of['quarterRgbaMismatches','cellRgbaMismatches','maskMismatches','bodyPixelMismatches','paletteOrAlphaFailures','atlasPixelMismatches'])verify(checks.finalExports[field]===0,'Final native export failure: '+field,checks.finalExports[field]);
verify(checks.ports.rgbaMismatches===0&&checks.ports.unexpectedInnerFinPixels===0,'Directional corner attachment or internal-hole fin regression failed',checks.ports);
checks.smallHoleRegression={caseTemplates:32,styles:20,cases:0,cellsCompared:0,emptyCells:0,innerCorners:0,topologyMismatches:0,chunkResolutionMismatches:0,rgbaMismatches:0,variantsUsed:[],templates:[]};const variantsUsed=new Set();
for(const size of[1,2])for(const origin of[{x:0,y:0},{x:-1,y:-1},{x:-17,y:-18},{x:17,y:18}])for(const seed of[0,1,2,3]){const width=size+4,rows=Array.from({length:width},(_,y)=>Array.from({length:width},(_,x)=>x>=2&&x<size+2&&y>=2&&y<size+2?'.':'#').join('')),grid=occupancyFromRows(rows,origin),chunks=partitionOccupancy(grid.occupied),across=(x,y)=>[...chunks.values()].some(c=>c.has(`${x},${y}`));let corners=0;for(let ly=0;ly<width;ly++)for(let lx=0;lx<width;lx++){const x=origin.x+lx,y=origin.y+ly,r=resolveCell(grid.occupied,x,y),t=topology(grid.occupied,x,y);if(!t){verify(r===null,'An empty hole received a sprite',{size,origin,seed,x,y});checks.smallHoleRegression.emptyCells+=20;continue;}if(r.rawMask!==t.raw||r.canonicalMask!==t.mask)checks.smallHoleRegression.topologyMismatches++;if(!same(resolveCell(across,x,y),r))checks.smallHoleRegression.chunkResolutionMismatches++;const v=resolveVariant(x,y,seed),expectedV=mod(x+(seed&1),2)+2*mod(-y+((seed>>1)&1),2);verify(v===expectedV,'Negative/chunk-coordinate global phase mismatch',{x,y,seed,v,expectedV});variantsUsed.add(v);corners+=r.quadrants.filter(q=>q.state==='INNER').length;for(const style of lookup.styles){const expected=assemble(moduleSets.get(style.styleId)[v],getQuadrants(t.mask)),actual=cellSets.get(style.styleId)[v].get(t.mask);checks.smallHoleRegression.rgbaMismatches+=compare(actual,expected,'Small-hole '+style.styleId+'/'+size+'/'+origin.x+','+origin.y+'/seed'+seed+'/cell'+x+','+y);checks.smallHoleRegression.cellsCompared++;}}verify(corners===4,'Small square hole must produce exactly four internal vertices',{size,origin,seed,corners});checks.smallHoleRegression.innerCorners+=corners*20;checks.smallHoleRegression.cases+=20;checks.smallHoleRegression.templates.push({size,origin,seed,chunks:chunks.size,rows,innerVertices:corners});}
checks.smallHoleRegression.variantsUsed=[...variantsUsed].sort();verify(checks.smallHoleRegression.cases===640&&variantsUsed.size===4&&checks.smallHoleRegression.topologyMismatches===0&&checks.smallHoleRegression.chunkResolutionMismatches===0&&checks.smallHoleRegression.rgbaMismatches===0,'All-theme small-hole/global-phase/chunk regression failed',checks.smallHoleRegression);
const report={pass:failureCount===0,artVersion:lookup.artVersion,baseline:preservation.provenance.sourcePackage,preservationMode:checks.preservationAuthority.mode,method:'Independent declaration-derived native body/role planes, complete attachment port vectors, exact RGBA body preservation, 640 negative-coordinate/chunk-seam small-hole scenarios; immutable v5 T01_A/source/motif PNG-byte comparison. Read-only art audit.',elapsedMilliseconds:Math.round(performance.now()-start),checks,failureCount,errors,limitations:['No Unity runtime or editor execution in this workspace.','Color cluster statistics are review candidates; they do not automatically classify every artistic jaggy/double.','T01_A uses the accepted v5 role geometry unchanged; the 19 newly revised styles use the v6 intersection policy.']};await fs.mkdir(path.dirname(REPORT),{recursive:true});await fs.writeFile(REPORT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({pass:report.pass,failureCount,revisedStyles:checks.revisedStyles.length,lockedT01AByteMismatches:checks.lockedT01A.byteMismatches,finalExports:checks.finalExports,ports:checks.ports,smallHoleCases:checks.smallHoleRegression.cases,smallHoleCellsCompared:checks.smallHoleRegression.cellsCompared,preservationMode:checks.preservationAuthority.mode,report:path.relative(ROOT,REPORT)},null,2));if(failureCount)process.exitCode=1;
