// Preconditions: validation COPY open, v2, Rect tool, ProbeWorld=(32.5,12.5), repaint completed.
var v=ANIMOL.Editor.TerrainEditorSceneEditor.View;v.Focus();var adapter=ANIMOL.Editor.TerrainEditorSceneEditor.Adapter;var map=adapter.Map;
ANIMOL.Editor.TerrainEditorSceneEditor.Cancel(false);ANIMOL.Editor.TerrainEditorSceneEditor.State.freeTool="Rect";
v.LookAtDirect(new UnityEngine.Vector3(14,3,0),UnityEngine.Quaternion.identity,20);
ANIMOL.Editor.TerrainEditorSceneEditor.ProbeWorld=new UnityEngine.Vector2(32.5f,12.5f);
v.SendEvent(new UnityEngine.Event{type=UnityEngine.EventType.Repaint});
var beforeHash=map.ContentHash;var beforeRevision=map.AuthoringRevision;int count=map.FreeShapeTerrain.cells.Count;
var original=map.FreeShapeTerrain.cells.Select(c=>c.Position).ToHashSet();
var start=ANIMOL.Editor.TerrainEditorSceneEditor.ProbeGui;float step=v.camera.pixelHeight/(2*v.camera.orthographicSize)/UnityEditor.EditorGUIUtility.pixelsPerPoint;
if(start.x<0 || start.x>v.position.width || start.y<40 || start.y>600)throw new System.Exception("Scene probe outside canvas: "+start);
var end=start+new UnityEngine.Vector2(3*step,-2*step);
System.Action<UnityEngine.Vector2,UnityEngine.EventType> mouse=(p,t)=>v.SendEvent(new UnityEngine.Event{type=t,button=0,mousePosition=p});
System.Action<UnityEngine.KeyCode> key=k=>v.SendEvent(new UnityEngine.Event{type=UnityEngine.EventType.KeyDown,keyCode=k,control=k==UnityEngine.KeyCode.Z||k==UnityEngine.KeyCode.Y});
mouse(start,UnityEngine.EventType.MouseDown);if(map.AuthoringRevision!=beforeRevision)throw new System.Exception("MouseDown changed map");
mouse(end,UnityEngine.EventType.MouseDrag);if(map.AuthoringRevision!=beforeRevision)throw new System.Exception("MouseDrag changed map");
mouse(end,UnityEngine.EventType.MouseUp);if(map.AuthoringRevision!=beforeRevision+1 || map.FreeShapeTerrain.cells.Count!=count+12)throw new System.Exception("Paint transaction mismatch: "+ANIMOL.Editor.TerrainEditorSceneEditor.Status);
var painted=map.FreeShapeTerrain.cells.Where(c=>!original.Contains(c.Position)).Select(c=>c.Position).ToArray();
var hole=new UnityEngine.Vector2Int(painted.Min(p=>p.x)+1,painted.Min(p=>p.y)+1);
key(UnityEngine.KeyCode.Z);if(map.ContentHash!=beforeHash)throw new System.Exception("Native undo failed");key(UnityEngine.KeyCode.Y);if(map.FreeShapeTerrain.cells.Count!=count+12)throw new System.Exception("Native redo failed");
ANIMOL.Editor.TerrainEditorSceneEditor.State.freeTool="Erase";var middle=start+new UnityEngine.Vector2(step,-step);mouse(middle,UnityEngine.EventType.MouseDown);mouse(middle,UnityEngine.EventType.MouseUp);
if(map.FreeShapeTerrain.cells.Count!=count+11 || map.FreeShapeTerrain.cells.Any(c=>c.Position==hole))throw new System.Exception("Internal hole erase failed");
var holeHash=map.ContentHash;
ANIMOL.Editor.TerrainEditorSceneEditor.State.freeTool="Select";mouse(start,UnityEngine.EventType.MouseDown);mouse(start+new UnityEngine.Vector2(-2*step,0),UnityEngine.EventType.MouseDrag);mouse(start+new UnityEngine.Vector2(-2*step,0),UnityEngine.EventType.MouseUp);
if(map.FreeShapeTerrain.cells.Count!=count+11 || map.ContentHash==holeHash)throw new System.Exception("Component move failed");
var movedHash=map.ContentHash;key(UnityEngine.KeyCode.Delete);if(map.FreeShapeTerrain.cells.Count!=count)throw new System.Exception("Delete component failed");
key(UnityEngine.KeyCode.Z);if(map.ContentHash!=movedHash)throw new System.Exception("Delete undo failed");
key(UnityEngine.KeyCode.Z);if(map.ContentHash!=holeHash)throw new System.Exception("Move undo failed");
key(UnityEngine.KeyCode.Z);key(UnityEngine.KeyCode.Z);
if(map.ContentHash!=beforeHash || map.AuthoringRevision!=beforeRevision)throw new System.Exception("Restoring verification strokes failed");
adapter.Save();
var result=new{artVersion=map.FreeShapeTerrain.artVersion,nativeMousePaint=true,noCommitUntilMouseUp=true,nativeEraseHole=true,holeCell=hole.ToString(),nativeComponentMove=true,nativeDelete=true,nativeKeyboardUndoRedo=true,verificationStrokesUndone=true,count=count,revision=map.AuthoringRevision,hash=map.ContentHash};
System.IO.File.WriteAllText("Docs/Validation/CleanArtV2/SceneInput.json",Newtonsoft.Json.JsonConvert.SerializeObject(result,Newtonsoft.Json.Formatting.Indented));return result;
